spring:
  application:
    name: Any Task Interview

# ============================================
#             Mail Configuration (SMTP)
# ============================================
  mail:
    host: smtp.gmail.com
    port: 587
    username: sendEmail@gmail.com #Replace With Your Email (Don't forget to disable Antivirus, as it blocks sending the email locally)
    password: passwordValue #Replace With your Password (App Password)
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true

# ============================================
#             CORS Configuration
# ============================================
  web:
    cors:
      mappings:
        - path-pattern: /**
          allowed-origins: "http://localhost:8080"
          allowed-methods: "GET,POST,PUT,DELETE"
          allowed-headers: "*"

# ============================================
#             Database Configuration
# ============================================
  datasource:
    url: jdbc:postgresql://localhost:5432/localDB?currentSchema=public
    driverClassName: org.postgresql.Driver
    username: sqlUser
    password: sqlPassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
      format-sql: true

# ============================================
#             JWT Configuration
# ============================================
task:
  jwt:
    secret-key: sQ0mFq5mHFw8ErK3Xa4qL8KJKYmM2ZcOTTKLf2QYvJE=
    ttl: 36000000 # 10hrs

# ============================================
#             Rate Limiting Configuration
# ============================================
  rate-limit:
    request-duration: 1 #1 minute
    max-request-count: 15 #15 requests per 1 minute

# ============================================
#             Notification Configuration
# ============================================
  notification:
    buffered-days: 8
# ============================================
#             Logging Configuration
# ============================================
logging:
  level:
    root: INFO
    com.technical.task: DEBUG

# ============================================
#             Actuator (Swagger) Configuration
# ============================================
springdoc:
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui

